### ISSUE TITLE
heroku state crashed (arrow functions)

### ISSUE THREAD

**Issue by Husterknupp** [Husterknupp/wordbraina#6]
```
2016-03-19T07:29:04.510362+00:00 heroku[web.1]: State changed from starting to crashed
2016-03-19T07:29:04.498821+00:00 heroku[web.1]: Process exited with status 1
2016-03-19T13:05:19.740454+00:00 heroku[web.1]: State changed from crashed to starting
2016-03-19T13:05:21.281652+00:00 heroku[web.1]: Starting process with command `node index.js`
2016-03-19T13:05:24.124324+00:00 app[web.1]: }).on('line', word => {
2016-03-19T13:05:24.124277+00:00 app[web.1]: /app/index.js:18
2016-03-19T13:05:24.124325+00:00 app[web.1]:                    ^^
2016-03-19T13:05:24.124338+00:00 app[web.1]: SyntaxError: Unexpected token =>
2016-03-19T13:05:24.124340+00:00 app[web.1]:     at Module._compile (module.js:443:25)
2016-03-19T13:05:24.124339+00:00 app[web.1]:     at exports.runInThisContext (vm.js:73:16)
2016-03-19T13:05:24.124348+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:478:10)
2016-03-19T13:05:24.124349+00:00 app[web.1]:     at Module.load (module.js:355:32)
2016-03-19T13:05:24.124349+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2016-03-19T13:05:24.124350+00:00 app[web.1]:     at Function.Module.runMain (module.js:501:10)
2016-03-19T13:05:24.124350+00:00 app[web.1]:     at startup (node.js:129:16)
2016-03-19T13:05:24.124351+00:00 app[web.1]:     at node.js:814:3
2016-03-19T13:05:25.113212+00:00 heroku[web.1]: State changed from starting to crashed
2016-03-19T13:05:25.111917+00:00 heroku[web.1]: Process exited with status 1
```

It works on my machine though.
- [x] teach heroku to work with ECMA 2015

**Comment by Husterknupp** [comment]
Heroku resources
https://devcenter.heroku.com/articles/nodejs-support
https://devcenter.heroku.com/articles/troubleshooting-node-deploys

Hope its the node version.. Change to v5.4.x

**Comment by Husterknupp** [comment]
That was it. Works again. Fixed.

```
2016-03-19T15:09:26.429957+00:00 heroku[api]: Deploy 8178d51 by husterknupp@outlook.com
2016-03-19T15:09:26.429957+00:00 heroku[api]: Release v20 created by husterknupp@outlook.com
2016-03-19T15:09:27.005568+00:00 heroku[web.1]: State changed from crashed to starting
2016-03-19T15:09:28.382254+00:00 heroku[web.1]: Starting process with command `node index.js`
2016-03-19T15:09:30.584367+00:00 app[web.1]: Node app is running on port 47912
2016-03-19T15:09:32.075726+00:00 heroku[web.1]: State changed from starting to up
```
